# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("a listed lie pays the keeper instead of the misled asker",
     "            self._credit(self.questions[gid + \":\" + str(position)].asker, share)",
     "            self._credit(keeper, share)"),
    ("lie share uses the wrong divisor (bond // 6)",
     "        share = bond // LIE_SHARE_DIVISOR\n", "        share = bond // (LIE_SHARE_DIVISOR + 1)\n"),
    ("six positions paid instead of five (cap off by one)",
     "lies[:LIE_SHARE_DIVISOR]", "lies[:LIE_SHARE_DIVISOR + 1]"),
    ("keeper gets the whole bond back despite the payouts",
     "        self._credit(keeper, bond - paid)", "        self._credit(keeper, bond)"),
    ("fail-safe flipped on unparseable output (every reply listed)",
     "                    return {\"lies\": []}\n            if not isinstance(data, dict):",
     "                    return {\"lies\": list(range(1, q_count + 1))}\n            if not isinstance(data, dict):"),
    ("an out-of-range position is skipped instead of voiding the list",
     "        if position < 1 or position > q_count:\n            return []",
     "        if position < 1 or position > q_count:\n            continue"),
    ("a non-number element is skipped instead of voiding the list",
     "        else:\n            return []\n        if position < 1",
     "        else:\n            continue\n        if position < 1"),
    ("validator accepts any well-formed list",
     "                return mine.get(\"lies\") == leader_lies", "                return True"),
    ("anyone may answer",
     "        if caller != str(record.keeper).lower():\n            raise gl.vm.UserError(\"Only the keeper may answer\")",
     "        if caller == \"\":\n            raise gl.vm.UserError(\"Only the keeper may answer\")"),
    ("anyone may reveal",
     "        if caller != keeper:\n            raise gl.vm.UserError(\"Only the keeper may reveal\")",
     "        if caller == \"\":\n            raise gl.vm.UserError(\"Only the keeper may reveal\")"),
    ("anyone may forfeit",
     "        if caller not in askers:", "        if False:"),
    ("forfeit deadline off by one (four days)",
     "        if self._today() < int(record.opened_day) + REVEAL_DAYS:",
     "        if self._today() <= int(record.opened_day) + REVEAL_DAYS:"),
    ("forfeit remainder lost",
     "        self._credit(caller, bond - share * len(askers))\n", ""),
    ("a second question may be asked while one is pending",
     "        if record.pending:\n            raise gl.vm.UserError(\"Wait for the keeper to answer the last question\")",
     "        if False:\n            raise gl.vm.UserError(\"Wait for the keeper to answer the last question\")"),
    ("reveal allowed while a question is pending",
     "        if record.pending:\n            raise gl.vm.UserError(\"Answer the last question before revealing\")",
     "        if False:\n            raise gl.vm.UserError(\"Answer the last question before revealing\")"),
    ("question cap off by one (21 questions)",
     "        if int(record.q_count) >= MAX_QUESTIONS:", "        if int(record.q_count) > MAX_QUESTIONS:"),
    ("question length cap off by one",
     "        if len(clean) > MAX_QUESTION_LENGTH:", "        if len(clean) >= MAX_QUESTION_LENGTH:"),
    ("minimum bond off by one",
     "        if bond < MIN_BOND_WEI or bond > MAX_BOND_WEI:", "        if bond <= MIN_BOND_WEI or bond > MAX_BOND_WEI:"),
    ("reserved token not checked on questions",
     "            raise gl.vm.UserError(\"Question is too long\")\n        if self._contains_reserved_token(clean):",
     "            raise gl.vm.UserError(\"Question is too long\")\n        if False:"),
    ("fence strip: no gap and a single pass (cross-token rebuild survives)",
     "            cleaned = cleaned[:index] + \" \" + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        # Fixed point: repeat until nothing changes, so nested fragments\n        # such as \"<<TAG>TAG>\" cannot rebuild a marker after one pass.\n        cleaned = value\n        while True:\n            before = cleaned\n            for token in RESERVED_TOKENS:\n                cleaned = self._remove_token(cleaned, token)\n            if cleaned == before:\n                return \" \".join(cleaned.split())",
     "            cleaned = cleaned[:index] + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        cleaned = value\n        for token in RESERVED_TOKENS:\n            cleaned = self._remove_token(cleaned, token)\n        return \" \".join(cleaned.split())"),
    ("wallet leaks into the prompt",
     "        safe_secret = self._fence_strip(secret)",
     "        safe_secret = self._fence_strip(secret) + \" \" + str(gl.message.sender_address)"),
    ("commitment skips whitespace normalization",
     "\"TWENTY_ASKS:SECRET:V1|\" + self._normalize_text(secret).lower()", "\"TWENTY_ASKS:SECRET:V1|\" + secret.strip().lower()"),
    ("state checked after caller in answer",
     "        if record.state != G_ASKING:\n            raise gl.vm.UserError(\"This game is over\")\n        caller = str(gl.message.sender_address).lower()\n        if caller != str(record.keeper).lower():",
     "        caller = str(gl.message.sender_address).lower()\n        if caller != str(record.keeper).lower():\n            raise gl.vm.UserError(\"Only the keeper may answer\")\n        if record.state != G_ASKING:\n            raise gl.vm.UserError(\"This game is over\")\n        if caller != str(record.keeper).lower():"),
    ("the latest correct guess wins instead of the earliest",
     "                winner = wallet\n                break\n", "                winner = wallet\n"),
    ("guesses shown before the reveal",
     "        if revealed:\n            for index in range(1, total + 1):", "        if True:\n            for index in range(1, total + 1):"),
    ("withdraw does not zero the credit",
     "        self.credits[caller] = u256(0)", "        self.credits[caller] = u256(amount)"),
    ("one wallet may guess twice",
     "        if key in self.guesses:", "        if False:"),
    ("day arithmetic treats February as part of the year",
     "        y -= m <= 2\n", "        y -= m < 2\n"),
]
